Repository LoginRadius/docs, pull requests merged in 2020-10, with the labels that each got.

#58 Fixed typos and mistakes in documentation
  content/guides/web-java.mdx
  content/guides/web-php.mdx
  content/mobile-sdk-libraries/android-library.mdx
  content/mobile-sdk-libraries/ios-library.mdx
Labels: hacktoberfest-accpeted

#37 Fixed Favicon issue in Docs by adding withPrefix
  src/gatsby-theme-apollo-docs/components/custom-seo.js
Labels: Ready for Merge

#53 Fixing React Native summary and description
  content/mobile-sdk-libraries/react-native-library.mdx
Labels: Ready for Merge, in review

#52 Fix broken link in docs/developer/mobile-sdk-libraries/ios-library
  content/mobile-sdk-libraries/ios-library.mdx
Labels: Ready for Merge, hacktoberfest-accepted

#32 Updated README.md
  README.md
Labels: Ready for Merge

#40 Linked Contributing Guidelines
  README.md
Labels: Ready for Merge
